# 1. docker compose up essaie de trouver les images dans le docker hub (pulic)
# 2. sinon si les images sont en local on les utilise SAUF si on demande explicitement un --build si la section build
# 3. sinon on peut builder les images avec la section build:

networks:
  stack-java:
    name: stack-java
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  httpd:
    container_name: stack-java-httpd
    image: 127.0.0.1:443/stack-java-httpd:2.4
    build:
      context: ./httpd
      # dockerfile: Dockerfile
    networks:
      - stack-java
    ports:
      - 8080:80
    depends_on:
      - tomcat
    develop:
      watch:
        # pour le code ou build: transfert d'un fichier/build modifié dans le conteneur + docker restart
        # - action: sync+restart
        #   # sur le host
        #   path: ./httpd/java_app.conf
        #   # dans le conteneur
        #   target: /usr/local/apache2/conf/sites/java_app.conf
        # changer le Dockerfile => il faut la section build
        - action: rebuild
          path: ./httpd/java_app.conf
          target: /usr/local/apache2/conf/sites/java_app.conf
  
  tomcat:
    container_name: stack-java-tomcat
    image: 127.0.0.1:443/stack-java-tomcat:9
    # build:
    #   context: ./tomcat
    #   args:
    #     - TOMCAT_VERSION_FULL=${TOMCAT_VERSION_FULL:-9.0.109}
    networks:
      - stack-java